name: build and test

on:
  push:
  pull_request:
    types:
      - ready_for_review
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "8.x"

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        working-directory: CalorieBurningApp.Server
        run: dotnet restore

      - name: Build
        working-directory: CalorieBurningApp.Server
        run: dotnet build

      - name: Install dependencies for xUnit tests
        working-directory: CalorieBurningApp.Server.Tests
        run: dotnet restore

      - name: Test
        working-directory: CalorieBurningApp.Server.Tests
        run: dotnet test
