name: build and test

on:
  push:
  pull_request:
    types:
      - ready_for_review
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "6.0.401"

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up working directory
        run: cd CalorieBurningApp.Server
        working directory: ./CalorieBurningApp.Server

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Set up working directory for xUnit tests
        run: cd CalorieBurningApp.Tests
        working-directory: ./CalorieBurningApp.Tests

      - name: Install dependencies for xUnit tests
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
