name: build and test

on:
  push:
  pull_request:
    types:
      - ready_for_review
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "8.x"

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ..\..\CalorieBurningApp.Server\CalorieBurningApp.Server.csproj

      - name: Build
        run: dotnet build ..\..\CalorieBurningApp.Server\CalorieBurningApp.Server.csproj

      - name: Install dependencies for xUnit tests
        run: dotnet restore ..\..\CalorieBurningApp.Server.Tests\CalorieBurningApp.Server.Tests.csproj

      - name: Test
        run: dotnet test ..\..\CalorieBurningApp.Server.Tests\CalorieBurningApp.Server.Tests.csproj
