name: build-and-test

on:
  pull_request:
    types:
      - ready_for_review
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "8.x"

jobs:
  build-and-test-dotnet:
    name: build-and-test-dotnet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dotnet dependencies
        working-directory: CalorieBurningApp.Server
        run: dotnet restore

      - name: Dotnet Build
        working-directory: CalorieBurningApp.Server
        run: dotnet build

      - name: Install xUnit dependencies
        working-directory: CalorieBurningApp.Server.Tests
        run: dotnet restore

      - name: Dotnet test
        working-directory: CalorieBurningApp.Server.Tests
        run: dotnet test
