name: build-and-test

on:
  pull_request:
    types:
      - ready_for_review
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "8.x"

jobs:
  build-and-test-dotnet:
    name: build-and-test-dotnet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dotnet dependencies
        working-directory: CalorieBurningApp.Server
        run: dotnet restore

      - name: Dotnet Build
        working-directory: CalorieBurningApp.Server
        run: dotnet build

      - name: Install xUnit dependencies
        working-directory: CalorieBurningApp.Server.Tests
        run: dotnet restore

      - name: Dotnet test
        working-directory: CalorieBurningApp.Server.Tests
        run: dotnet test

      - name: Npm (React) dependencies
        working-directory: calorieburningapp.client
        run: |
          npm install

      - name: Npm (React) Build
        working-directory: calorieburningapp.client
        run: npm run build

      - name: Check job status and update pull request
        if: ${{ failure() }}
        run: |
          echo "::error::One or more jobs failed. Please fix the issues before marking this pull request as ready for review."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"body": "One or more jobs failed. Please fix the issues before marking this pull request as ready for review."}' \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"draft": true}' \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
